---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: mystream  
  namespace: nats
  labels:
    hello: world
spec:
  name: mystream
  subjects: ["orders.*"]
  storage: memory
  maxAge: 1h
  replicas: 1
